name: Destroy

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Reason?"
        required: true

jobs:
  stagingDestroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Staging Destroy
      - run: echo "Run Terraform Destroy for Staging"

  productionDestroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'

    steps:
      - uses: actions/checkout@v2

      - name: Staging Destroy
      - run: echo "Run Terraform Destroy for Staging"
