name: Destroy

on:
  # note: it only will be available
  # to use when it's available on master branch.
  workflow_dispatch:
    inputs:
      tags:
        description: "Reason?"
        required: true

jobs:
  stagingDestroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Staging Destroy
        run: |
          cd deploy/
          terraform init
          terraform select workspace staging
          terraform destroy -auto-approve

  productionDestroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Production Destroy
        run: |
          cd deploy/
          terraform init
          terraform select workspace production
          terraform destroy -auto-approve
